name: Test and deploy the api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node v${{ matrix.node-version }} ğŸ§‘ğŸ»â€ğŸ’»
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies ğŸ‘ª
        run: npm ci

      - name: Lint & format code ğŸ§¹
        run: npm run lint && npm run format

      - name: Build app ğŸ› 
        run: npm run build

      - name: Run unit tests ğŸ‘®â€â™€ï¸
        run: npm run test

      # Zips the deploy package
      - name: Generate deployment package ğŸ‘·ğŸ»â€â™‚ï¸
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir deployment
          cp -r dist deployment
          cp package* deployment
          cp .nvmrc deployment
          cd deployment

      # Deploys the package to Heroku
      - name: Deploy to Heroku ğŸš€
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: 'deployment'
