name: Test and deploy the api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node v${{ matrix.node-version }} ğŸ§‘ğŸ»â€ğŸ’»
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies ğŸ‘ª
        run: npm ci

      - name: Lint & format code ğŸ§¹
        run: npm run lint && npm run format

      - name: Build app ğŸ› 
        run: npm run build

      - name: Run unit tests ğŸ‘®â€â™€ï¸
        run: npm run test

      # Zips the deploy package
      - name: Generate deployment package ğŸ‘·ğŸ»â€â™‚ï¸
        if: github.ref == 'refs/heads/main'
        run: |
          cd dist
          zip -r deploy.zip . -x '*.git*'

      # Deploys the package to AWS EB
      - name: Deploy to EB ğŸ“¤
        if: github.ref == 'refs/heads/main'
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: socialife
          environment_name: socialife-prod-env
          version_label: ${{ github.run_id }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: dist/deploy.zip
